spring.config.import=optional:file:.env[.properties]

spring.application.name=${SERVICE_REGISTRY_APP_NAME}
server.port=${PORT:9000}

eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

app.cors.frontend.allowed-origins=${FRONTEND_ALLOWED_ORIGINS}