spring.config.import=optional:file:.env[.properties]

spring.application.name=${INVENTORY_SERVICE_APP_NAME}
server.port=${PORT:5000}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=${EUREKA_SERVER}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}

api.gateway.key=${API_GATEWAY_KEY}

app.cors.frontend.allowed-origins=${FRONTEND_ALLOWED_ORIGINS}

# Redis
spring.data.redis.url=${REDIS_URL}
app.redis.stream=${REDIS_STREAM_NAME}
app.redis.group=${REDIS_CONSUMER_GROUP}
app.redis.consumer=${REDIS_CONSUMER_NAME}